version: "2"
services:

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: docker_root
      MYSQL_DATABASE: chessstats
      MYSQL_PASSWORD: chessstats
      MYSQL_USER: chessstats
    volumes: 
      - mysql_data:/var/lib/mysql
    ports:
      - "3307:3306"

  api_server:
    depends_on:
      - mysql
    build: ./server
    ports:
      - "8081:8080"
    entrypoint: sh -c "/wait-for-port.sh mysql 3306 && sleep 3 && java -jar /app.jar"
  
  client:
    # depends_on:
      # - api_server
    build: ./client
    #volumes: 
      #- "./client:/chess-stats-client" # for HMR
      #- "./chess-stats-client/node_modules" # save container node_modules visibility
    ports:
      - 8082:8082 # HMR seems to be not working when ports are not same
  
volumes:
  mysql_data:
