version: "2"
services:

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: docker_root
      MYSQL_DATABASE: chessstats
      MYSQL_PASSWORD: chessstats
      MYSQL_USER: chessstats
    ports:
      - "3307:3306"

  api_server:
    depends_on:
      - mysql
    build: ./server
    ports:
      - "8081:8080"
    entrypoint: sh -c "/wait-for-port.sh mysql 3306 && sleep 3 && java -jar /app.jar"
  
  client:
    # depends_on:
      # - api_server
    build: ./client
    volumes: 
      - "./client:/chess-stats-client"
    stdin_open: true
    tty: true
    ports:
      - 8082:8082 # для HMR порты должны совпадать
    entrypoint: ["quasar", "dev"]
